WL_RandomLoadoutConfig {
 m_aFactions {
  WL_FactionLoadoutConfig {
   m_sFactionKey "US"
   m_aSlots {
    WL_SlotPool {
     m_sSlotName "Helmet"
     m_eAreaType 3
     m_bEnabled 1
     m_aItems {
     }
    }
   }
  }
  WL_FactionLoadoutConfig {
   m_sFactionKey "USSR"
   m_aSlots {
    WL_SlotPool {
     m_sSlotName "Helmet"
     m_eAreaType 3
     m_bEnabled 1
     m_aItems {
     }
    }
   }
  }
  WL_FactionLoadoutConfig {
   m_sFactionKey "FIA"
   m_aSlots {
    WL_SlotPool {
     m_sSlotName "Helmet"
     m_eAreaType 3
     m_bEnabled 1
     m_aItems {
     }
    }
   }
  }
 }
}
