WL_RandomLoadoutConfig {
 m_aFactions {
  WL_FactionLoadoutConfig "{68D72AF91B9E7AE3}" {
   m_sFactionKey "US"
   m_aSlots {
    WL_SlotPool "{68D72AF9799C0774}" {
     m_eAreaType Helmet
     m_aItems {
      WL_WeightedItem "{68D72AF9709E1FAC}" {
       m_sPrefab "{6E14F80C250F85FC}Prefabs/Characters/HeadGear/Helmet_M1_01/Helmet_M1_01.et"
      }
     }
    }
   }
  }
  WL_FactionLoadoutConfig "{68D72AF91B27816B}" {
   m_sFactionKey "USSR"
   m_aSlots {
    WL_SlotPool "{68D72AF97B580698}" {
     m_eAreaType Helmet
     m_aItems {
      WL_WeightedItem "{68D72AF94FD9E0BC}" {
       m_sPrefab "{A7E6D7ECD5F684D7}Prefabs/Characters/HeadGear/Helmet_SSh68_01/Helmet_SSh68_01.et"
      }
     }
    }
   }
  }
  WL_FactionLoadoutConfig "{68D72AF91AEBDA8E}" {
   m_sFactionKey "FIA"
   m_aSlots {
    WL_SlotPool "{68D72AF97DE92FE1}" {
     m_eAreaType Helmet
     m_aItems {
      WL_WeightedItem "{68D72AF9504233FC}" {
       m_sPrefab "{B02281435AED8274}Prefabs/Characters/HeadGear/Hat_M70_01/Hat_M70_01.et"
      }
     }
    }
   }
  }
 }
}